apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-manager-test
spec:
  commonName: ($ingress_host_name)
  dnsNames:
    - ($ingress_host_name)
  duration: 24h0m0s
  issuerRef:
    kind: Issuer
    name: cert-manager-test
  secretName: cert-manager-test
