apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-manager-test
spec:
  commonName: ($ingress_host_name)
  dnsNames:
    - ($ingress_host_name)
  duration: 2160h0m0s
  issuerRef:
    kind: ClusterIssuer
    name: ($issuer_name)
  secretName: ($issuer_name)
