# yaml-language-server: $schema=https://raw.githubusercontent.com/kyverno/chainsaw/main/.schemas/json/test-chainsaw-v1alpha1.json
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: cert-manager
spec:
  description:
    Creates cluster issuer and certificate.
  timeouts:
    exec: 30s
    apply: 30s
    delete: 1m
  namespaceTemplate:
    metadata:
      labels:
        chainsaw-test: ($values.test_name)
  bindings:
    - name: test_name
      value: ingress
    - name: ingress_host_name
      value: (join('.',[$namespace, env('BASE_DOMAIN')]))
  steps:
    - try:
        - apply:
            file: manifests/*

    - try:
        - wait:
            timeout: 5m
            apiVersion: cert-manager.io/v1
            kind: Issuer
            name: cert-manager-test
            for:
              condition:
                name: Ready
                value: "True"
        - wait:
            timeout: 5m
            apiVersion: cert-manager.io/v1
            kind: Certificate
            name: cert-manager-test
            for:
              condition:
                name: Ready
                value: "True"

  catch:
    - get:
        kind: Certificate
        apiVersion: cert-manager.io/v1
    - get:
        kind: Issuer
        apiVersion: cert-manager.io/v1
    - events: {}
    - podLogs:
        namespace: cert-manager
        timeout: 30s
        tail: 200
