# yaml-language-server: $schema=https://raw.githubusercontent.com/kyverno/chainsaw/main/.schemas/json/test-chainsaw-v1alpha1.json
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: coredns
spec:
  timeouts:
    exec: 30s
    apply: 30s
    delete: 1m
  namespaceTemplate:
    metadata:
      labels:
        chainsaw-test: ($values.test_name)
  bindings:
    - name: test_name
      value: coredns
  steps:
    - try:
        - apply:
            file: manifests/*
        - wait:
            timeout: 2m
            apiVersion: batch/v1
            kind: Job
            name: coredns-check-job
            for:
              condition:
                name: Complete
                value: "True"

  catch:
    - get:
        kind: Pod
        apiVersion: v1
    - get:
        kind: Job
        apiVersion: batch/v1
    - events: {}

