# yaml-language-server: $schema=https://raw.githubusercontent.com/kyverno/chainsaw/main/.schemas/json/test-chainsaw-v1alpha1.json
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: proxmox-csi
spec:
  steps:
    - try:
        - apply:
            file: manifests/*
        - assert:
            resource:
              apiVersion: v1
              kind: Pod
              metadata:
                labels:
                  app: test-proxmox-csi
              status:
                phase: Running
